### ISSUE TITLE
amr.py has no license info

### ISSUE THREAD

**Issue by goodmami** [rafaelanchieta/sema#3]
The amr.py file is copied (presumably) from [smatch](https://github.com/snowblink14/smatch/), but it does not include smatch's license text. This is a condition of the MIT license. I think just adding a comment at the top saying where the module came from with a link to smatch's [LICENSE.txt](https://github.com/snowblink14/smatch/blob/master/LICENSE.txt) is sufficient.

**Comment by rafaelanchieta** [comment]
I just update the amr.py file.

**Comment by goodmami** [comment]
Excellent. Thank you
